trigger_notification:
  name: "Trigger a notification on a notification group entity"
  description: "Trigger a visual notification pattern using the chosen notification group entity."
  fields:
    entity_id:
      description: "Select the notification group entity."
      required: true
      selector:
        entity:
          domain: button
          integration: notification_lights
    color:
      description: "Notification color (if supported) using a color picker."
      required: true
      selector:
        color_rgb: {}

