trigger_notification:
  name: "Trigger a notification on a light group"
  description: "Trigger a visual notification pattern using a specified notification group."
  fields:
    group_name:
      description: "Name of the notification group."
      required: true
      selector:
        text:
          multiline: false
    color:
      description: "Notification color (if supported) using a color picker."
      required: false
      selector:
        color_rgb: {}
    pattern_on:
      description: "Time (in seconds) for which lights stay ON in each pattern cycle."
      required: false
      default: 1.0
      selector:
        number:
          min: 0
          max: 10
          step: 0.1
          unit_of_measurement: "s"
    pattern_off:
      description: "Time (in seconds) for which lights stay OFF in each pattern cycle."
      required: false
      default: 1.0
      selector:
        number:
          min: 0
          max: 10
          step: 0.1
          unit_of_measurement: "s"
    pattern_repeat:
      description: "Number of times to repeat the pattern."
      required: false
      default: 3
      selector:
        number:
          min: 1
          max: 20
          step: 1
    duration:
      description: "Duration in seconds to hold the light state if no pattern is defined."
      required: false
      default: 10
      selector:
        number:
          min: 1
          max: 600
          step: 1
          unit_of_measurement: "s"
    restore:
      description: "Restore previous states after finishing?"
      required: false
      default: true
      selector:
        boolean: {}
