on:
  push:
    branches:
      - main

jobs:
  release-on-push:
    runs-on: ubuntu-latest
    env:
      GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
    steps:
      - uses: rymndhng/release-on-push-action@master
        with:
          bump_version_scheme: minor

#      - name: HACS validation
#        uses: "hacs/action@main"
#        with:
#          category: "integration"

permissions:
  contents: write
  pull-requests: read